### ISSUE TITLE
Emojis don't work

### ISSUE THREAD

**Issue by DuckMasterAl** [advaith1/slashtags#1]
The bot sends ":no:" or ":check:" instead of the proper emojis.
<img width="207" alt="Screen Shot 2020-12-23 at 11 13 53 PM" src="https://user-images.githubusercontent.com/43557963/103060022-cd6e1a80-4574-11eb-9da3-17ec638b07d6.png"> <img width="429" alt="Screen Shot 2020-12-23 at 11 14 29 PM" src="https://user-images.githubusercontent.com/43557963/103060026-ce9f4780-4574-11eb-9c94-419ac0f8418b.png">

**Comment by advaith1** [comment]
`@everyone` doesn't have the Use External Emojis permission in your server

**Comment by DuckMasterAl** [comment]
> `@everyone` doesn't have the Use External Emojis permission in your server

I guess it doesn't work if you give the bot admin. Weird...

**Comment by advaith1** [comment]
yeah slash command responses aren't affected by the bot's permissions

**Comment by RyanLua** [comment]
Can this issue be reconsidered? With the release of [application emojis](https://discord.com/developers/docs/change-log#application-emoji), you can now upload emojis for bots and not rely on external emojis.

**Comment by advaith1** [comment]
true, though giving `@everyone` the permission is not needed anymore anyway since now the bot permissions apply to interaction responses.
