### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by omxpro** [advaith1/slashtags#4]
![Screenshot_20210528-135558_Brave](https://user-images.githubusercontent.com/69719569/119955988-3f340f80-bfbe-11eb-836f-075ed4f340d5.jpg)
![Screenshot_20210528-135546_Brave](https://user-images.githubusercontent.com/69719569/119955995-40fdd300-bfbe-11eb-89af-501293bc20e4.jpg)
![Screenshot_20210528-134704_Brave](https://user-images.githubusercontent.com/69719569/119956000-41966980-bfbe-11eb-84ad-077204b3d831.jpg)
![Screenshot_20210528-134121_Brave](https://user-images.githubusercontent.com/69719569/119956003-422f0000-bfbe-11eb-8c01-e0260071b7b5.jpg)
![Screenshot_20210528-133844_Brave](https://user-images.githubusercontent.com/69719569/119956005-42c79680-bfbe-11eb-9b25-427efc49295b.jpg)
![Screenshot_20210528-125729_Brave](https://user-images.githubusercontent.com/69719569/119956007-43602d00-bfbe-11eb-9f65-5b6ea2b2842c.jpg)
![Screenshot_20210528-125721_Brave](https://user-images.githubusercontent.com/69719569/119956014-43f8c380-bfbe-11eb-8b4f-128a697dea25.jpg)
![Screenshot_20210528-125715_Brave](https://user-images.githubusercontent.com/69719569/119956020-44915a00-bfbe-11eb-9e2f-7bee96c250cc.jpg)
![Screenshot_20210528-121905_Brave](https://user-images.githubusercontent.com/69719569/119956024-4529f080-bfbe-11eb-98da-36cf41aeb2e7.jpg)

**Comment by omxpro** [comment]
![Screenshot_20210530-114921_Firefox Lite](https://user-images.githubusercontent.com/69719569/120094399-b643e200-c13d-11eb-9b2a-c26cc4bbf0c5.jpg)
![Screenshot_20210530-114911_Firefox Lite](https://user-images.githubusercontent.com/69719569/120094400-b7750f00-c13d-11eb-9d62-9519e91f662d.jpg)

**Comment by advaith1** [comment]
These all seem to be configuration issues, not actual issues with the code. I do not support self-hosting.
